import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ApolloClient, InMemoryCache } from '@apollo/client';
import { useRouter } from 'next/router';

import GetGlobalStrings from './../shared/graphql-cms/GetGlobalStrings';

export default function Home({ strings, locale, locales}) {
  let router = useRouter();


  return (
    <div className={styles.container}>
      <Head>
        <title>{strings.venueName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          
        {strings.venueName}
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}




/* DATA FETCHING -- (PRE-RENDERED VIA getStaticProps) */
export async function getStaticProps({ locale, locales }) {

  // NOTE: All configured locales inside of Next.js are the same as the locales configured
  // within Strapi

  const client = new ApolloClient({
    uri: process.env.CMS_GRAPHQL_ENDPOINT,
    cache: new InMemoryCache()
  });

  
  const { data } = await client.query({
    query: GetGlobalStrings(locale)
  });


  // handle graphql errors

  return {
    props: {
      strings: data.string,
      locale,
      locales
    }
  }
}